# Site settings
title: Amaia Giralt • Product Marketing
description: > # this means to ignore newlines until "baseurl:"
  Product marketer, design thinker and future growth hacker. Big fan of absurd humor and roadtrips. Come to say hello!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amaiagiralt.com" # the base hostname & protocol for your site

#Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  - assets/sass

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - github-pages
